Update webpack config so that cheerio behaves properly in conjunction with enzyme
Before making these changes calls to chai-enzyme assertions that depend on cheerio would result in an error message akin to "TypeError: '[object DOMWindow]' is not a function (evaluating '(0, _cheerio2.default)(html)’)". A similar error occurs when using cheerio directly.

It is unclear to me why we needed to add "text-encoding" to the externals. Changes were made following advice @ https://github.com/airbnb/enzyme/issues/47